swagger: '2.0'
info:
  description: "API for user login/register and chatbot"
  version: "1.0.0"
  title: "User & ChatBot"

host: 0.0.0.0
basePath: /v1

tags:
  - name: user
    description: function with user account
  - name: chatbot
    description: function with chat bot

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  
paths:
  /user/register:
    post:
      summary: register a new user
      tags:
      - user
      parameters:
        - in: body
          name: new_user
          description: username & password for new user
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        201:
          description: "Success"
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              userID:
                type: integer
        403:
          description: "Invalid input"
  /user/login:
    post:
      summary: login as a user
      tags:
      - user
      parameters:
        - in: body
          name: user info
          description: username & password 
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        201:
          description: "Success"
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              userID:
                type: integer
        404:
          description: "User not found"
  /chatbot/ask:
    get:
      summary: Chat with chatbot
      tags:
      - chatbot
      parameters:
        - in: query
          name: expression
          description: message input
          required: true
          type: string
        - in: query
          name: user_id
          description: current user id
          required: true
          type: integer
      responses:
        200:
          description: "Success"
          schema:
            type: string
        